! (v) Created by PCA*LIB
begin-sql -C1
set char_convert 'iso_1'
end-sql
begin-sql -C2
set char_convert 'iso_1'
end-sql
begin-sql -C3
set char_convert 'iso_1'
end-sql
begin-sql -C4
set char_convert 'iso_1'
end-sql
begin-sql -C5
set char_convert 'iso_1'
end-sql
begin-sql -C6
set char_convert 'iso_1'
end-sql
begin-sql -C7
set char_convert 'iso_1'
end-sql
begin-sql -C8
set char_convert 'iso_1'
end-sql
